# ✅ docker-compose.yml
version: '3.8'

services:

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8087:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3007:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb

  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - influxdb

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo_data:
  influx_data:
